routes/frontend.php
<?php

Route::get('/', function() {
    return view('frontend.index');
});

// Forbidden
Route::get('/', ['as' => 'frontend.index',
    'uses' => 'Frontend\IndexController@getIndex']);

Route::get('/services/', ['as' => 'frontend.service.index',
    'uses' => 'Frontend\ArticleController@getServiceIndex']);

Route::get('/hizmetler/', ['as' => 'frontend.service.index',
    'uses' => 'Frontend\ArticleController@getServiceIndex']);

Route::get('/hizmetler/{slug}', ['as' => 'frontend.service.detail',
    'uses' => 'Frontend\ArticleController@getServiceDetail']);

Route::get('/services/{slug}', ['as' => 'frontend.service.detail',
    'uses' => 'Frontend\ArticleController@getServiceDetail']);

Route::get('/kurumsal/{slug}', ['as' => 'frontend.page.detail',
    'uses' => 'Frontend\ArticleController@getPageDetail']);

Route::get('/corporative/{slug}', ['as' => 'frontend.page.detail',
    'uses' => 'Frontend\ArticleController@getPageDetail']);

Route::get('/products/', ['as' => 'frontend.product.index',
    'uses' => 'Frontend\ProductController@index']);

Route::get('/urunler/{category?}', ['as' => 'frontend.product.category.detail',
    'uses' => 'Frontend\ProductController@index']);

Route::get('/urunler/detay/{slug}', ['as' => 'frontend.products.show',
    'uses' => 'Frontend\ProductController@show']);

Route::get('/our-news', ['as' => 'frontend.blog.index',
    'uses' => 'Frontend\BlogController@index']);

Route::get('/bizden-haberler', ['as' => 'frontend.blog.index',
    'uses' => 'Frontend\BlogController@index']);

Route::get('/our-news/{id}', ['as' => 'frontend.blog.show',
    'uses' => 'Frontend\BlogController@show']);

Route::get('/haberler/{id}', ['as' => 'frontend.blog.show',
    'uses' => 'Frontend\BlogController@show']);

Route::get('/bizden-haberler/{id}', ['as' => 'frontend.blog.show',
    'uses' => 'Frontend\BlogController@show']);

Route::get('/press', ['as' => 'frontend.blog.press.index',
    'uses' => 'Frontend\BlogController@indexPress']);

Route::get('/basinda-biz', ['as' => 'frontend.blog.press.index',
    'uses' => 'Frontend\BlogController@indexPress']);

Route::get('/press/{id}', ['as' => 'frontend.blog.show.press',
    'uses' => 'Frontend\BlogController@showPress']);

Route::get('/basinda-biz/{id}', ['as' => 'frontend.blog.show.press',
    'uses' => 'Frontend\BlogController@showPress']);

Route::get('/urunler/', ['as' => 'frontend.product.index',
    'uses' => 'Frontend\ProductController@index']);

Route::get('/contact/', ['as' => 'frontend.contact.index',
    'uses' => 'Frontend\ContactController@index']);

Route::get('/iletisim/', ['as' => 'frontend.contact.index',
    'uses' => 'Frontend\ContactController@index']);

Route::post('/send-contact-form/', ['as' => 'frontend.contact.post',
    'uses' => 'Frontend\ContactController@sendForm']);

Route::post('/abone/ekle', [
    'uses' => 'Frontend\SubscriberController@store', 'as' => 'frontend.subscriber.store'
]);

Route::get('/sayfalar/{slug}', ['as' => 'frontend.page.show',
    'uses' => 'Frontend\PageController@show']);

Route::get('/is-basvuru-formu', ['as' => 'frontend.ik.isbasvuru',
    'uses' => 'Frontend\PageController@isbasvuru']);

Route::post('/is-basvuru-formu', ['as' => 'frontend.ik.post',
    'uses' => 'Frontend\PageController@ikpost']);

Route::get('/staj-basvuru-formu', ['as' => 'frontend.ik.stajbasvuru',
    'uses' => 'Frontend\PageController@stajbasvuru']);

Route::post('/staj-basvuru-formu', ['as' => 'frontend.ik.stajbasvuru.post',
    'uses' => 'Frontend\PageController@stajpost']);

routes/web.php
<?php

Route::group(['prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]], function() {

    // Client/Frontend Routes
    require base_path('routes/frontend.php');

    // Authenticate
    require base_path('routes/modules/auth.php');
});


// Back-end Routes

Route::group(['middleware' => ['sentinel.auth', 'hasAccess', 'localeSessionRedirect', 'localizationRedirect' ],
    'prefix' => LaravelLocalization::setLocale(), 'as' => 'admin.'], function () {

    // Forbidden
    Route::get('admin/forbidden', ['as' => 'errors.forbidden',
        'uses' => 'Auth\SessionController@forbidden']);

    // Git Update
    Route::get('admin/git-update', ['as' => 'git.update',
        'uses' => 'GitController@update']);

    // Logs
    require base_path('routes/modules/logs.php');

    // Dashboard (Index/Google Analytics)
    require base_path('routes/modules/dashboard.php');
    
    // Settings
    require base_path('routes/modules/settings.php');

    // Users
    require base_path('routes/modules/users.php');

    // Roles
    require base_path('routes/modules/roles.php');

    // Photo Library
    require base_path('routes/modules/photo_library.php');

    // Category
    require base_path('routes/modules/categories.php');

    // Slides
    require base_path('routes/modules/slides.php');

    // Articles
    require base_path('routes/modules/articles.php');

    // Forms
    require base_path('routes/modules/forms.php');

    // Stores
    require base_path('routes/modules/stores.php');

    // Subscribers
    require base_path('routes/modules/subscribers.php');

    // Report
    require base_path('routes/modules/reports.php');

    // Products
    require base_path('routes/modules/products.php');

    // Campaigns
    require base_path('routes/modules/campaigns.php');

});

app/Form.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Form extends Model
{
    protected $table  = 'forms';
    protected $guarded = ['*'];
    protected $fillable = ['name', 'email', 'phone', 'subject', 'message', 'type',
        'list_id', 'active', 'city', 'district', 'notes'];

    public static function types($default = "Seçiniz")
    {
        $list = [
            '1' => 'Biz Sizi Arayalım',
            '2' => 'İletişim Formu',
        ];

        if ($default) $list[""] = $default;
        return $list;
    }

    public static function getFormType($formType) {
        $type = array_only(self::types(), [$formType]);
        return $type[$formType];
    }

    public function getUpdatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->diffForHumans();
    }
}

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.master')
@section('title', 'Smart Panel')
@section('css')
<style>
    .c3-axis-x text {
        font-size:11px;
    }

</style>
@endsection

@section('content')

    <div class="col-md-12">
        <!-- Quick stats boxes -->
        <div class="row">
            <div class="col-lg-3">

                <!-- Members online -->
                <div class="panel bg-slate">
                    <div class="panel-body">
                        <h3 class="no-margin">{{$visitors}}</h3>
                        Kullanıcılar
                        <div class="text-muted text-size-small">Google Analytics /  ({{ session('day', '30') }} Gün) </div>
                    </div>

                    <div class="container-fluid">
                        <div id="members-online"></div>
                    </div>
                </div>
                <!-- /members online -->

            </div>

            <div class="col-lg-3">
                <!-- Members online -->
                <div class="panel bg-pink">
                    <div class="panel-body">
                        <h3 class="no-margin">{{$pageviews}}</h3>
                        Sayfa Görüntülemeleri
                        <div class="text-muted text-size-small">Google Analytics /  ({{ session('day', '30') }} Gün) </div>
                    </div>

                    <div class="container-fluid">
                        <div id="members-online"></div>
                    </div>
                </div>
                <!-- /members online -->
            </div>

            <div class="col-lg-2">
                <!-- Current server load -->
                <div class="panel bg-blue">
                    <div class="panel-body">
                        <h3 class="no-margin">{{ \App\Helpers\System::getSystemLoad() }} %</h3>
                        CPU Kullanımı
                        <div class="text-muted text-size-small">Sunucu Yönetimi</div>
                    </div>
                </div>
                <!-- /current server load -->
            </div>

            <div class="col-lg-2">
                <!-- Current server load -->
                <div class="panel bg-indigo">
                    <div class="panel-body">
                        <h3 class="no-margin">{{ \App\Helpers\System::getServerMemory() }}</h3>
                        Bellek Kullanımı
                        <div class="text-muted text-size-small">Sunucu Yönetimi</div>
                    </div>
                </div>
                <!-- /current server load -->
            </div>

            <div class="col-lg-2">
                <!-- Current server load -->
                <div class="panel bg-orange-700 ">
                    <div class="panel-body">
                        <h3 class="no-margin">{{ $diskUsedSpace }} %</h3>
                        Disk: <b>{{ $diskFreeSpace }}</b>
                        <div class="text-muted text-size-small">Sunucu Yönetimi</div>
                    </div>
                </div>
                <!-- /current server load -->
            </div>

        </div>
        <!-- /quick stats boxes -->
    </div>

    <div class="col-md-12">
        <!-- Categorized axes -->
        <div class="panel panel-white">
            <div class="panel-heading">
                <h6 class="panel-title"><span class="text-highlight bg-primary">Oturumlar</span></h6>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-popup="tooltip" title="Menu"><i class="icon-three-bars"></i></a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li><a href="{{ route('admin.dashboard.show', ['day' => '7']) }}">7 Gün</a></li>
                                <li><a href="{{ route('admin.dashboard.show', ['day' => '15']) }}">15 Gün</a></li>
                                <li><a href="{{ route('admin.dashboard.show', ['day' => '30']) }}">30 Gün</a></li>
                                <li><a href="{{ route('admin.dashboard.show', ['day' => '60']) }}">60 Gün</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="panel-body">
                <div class="chart-container">
                    <div class="chart" id="c3-axis-categorized"></div>
                </div>
            </div>
        </div>
        <!-- /xategorized axes -->
    </div>
    <div class="col-md-4">
        <div class="panel panel-white">
            <div class="panel-heading">
                <h6 class="panel-title text-semibold"><span class="text-highlight bg-primary">Popüler Tarayıcı</span></h6>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="reload"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>

            <div class="panel-body">
                <div class="chart-container text-center">
                    <div class="display-inline-block" id="c3-donut-chart"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-white">
            <div class="panel-heading">
                <h6 class="panel-title text-semibold"><span class="text-highlight bg-primary">Ziyaretçi Kaynağı</span></h6>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="reload"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>

            <div class="panel-body">
                <div class="chart-container text-center">
                    <div class="display-inline-block" id="c3-donut-chart-2"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-white">
            <div class="panel-heading">
                <h6 class="panel-title text-semibold"><span class="text-highlight bg-primary">Ziyaretçi Trafiği</span></h6>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="reload"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>

            <div class="panel-body">
                <div class="chart-container text-center">
                    <div class="display-inline-block" id="user-types"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <!-- Table -->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title"><span class="text-highlight bg-primary">Sayfalara Göre Oturumlar</span></h5>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>

            <div class="table-responsive table-striped">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Sayfa Başlığı</th>
                        <th>Görüntülenme</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $count = 1; ?>
                    @foreach($mostVisitedPages as $mostVisitedPage)
                        @if ($count == 11)
                            @continue
                        @endif
                    <tr>
                        <td>{{ $count++ }}</td>
                        <td>{{$mostVisitedPage['pageTitle']}}</td>
                        <td><span class="badge bg-primary">{{$mostVisitedPage['pageViews']}}</span></td>
                    </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /table -->
    </div>
    <div class="col-md-6">
        <!-- Table -->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title"><span class="text-highlight bg-primary">Şehire Göre Oturumlar</span></h5>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>

            <div class="table-responsive table-striped">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Şehir</th>
                        <th>Görüntülenme</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $count = 1; ?>
                    @foreach($analyticsCity as $city)
                        <tr>
                            <td>{{ $count++ }}</td>
                            <td>{{$city[0]}}</td>
                            <td><span class="badge bg-primary">{{$city[1]}}</span></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /table -->
    </div>


    </div>


@endsection

@section('js')
<!-- Theme JS files -->

    <script type="text/javascript" src="/cms/js/plugins/visualization/d3/d3.min.js"></script>
    <script type="text/javascript" src="/cms/js/plugins/visualization/c3/c3.min.js"></script>
    <script type="text/javascript" src="/cms/js/core/app.js"></script>

    <script>
        var donut_chart = c3.generate({
            bindto: '#c3-donut-chart',
            size: { width: 300 },
            color: {
                pattern: ['#3F51B5', '#FF9800', '#4CAF50', '#00BCD4', '#F44336']
            },
            data: {
                columns: [
                        @foreach($browsers as $browser)
                    ['{{$browser['browser']}}', {{$browser['sessions']}}],
                        @endforeach
                ],
                type : 'donut'
            },
            donut: {
                title: "Popüler Tarayıcı"
            }
        });

        var donut_chart2 = c3.generate({
            bindto: '#c3-donut-chart-2',
            size: { width: 300 },
            color: {
                pattern: ['#3F51B5', '#FF9800', '#4CAF50', '#00BCD4', '#F44336']
            },
            data: {
                columns: [
                        @foreach($referrers as $referrer)
                    ['{{$referrer['url']}}', {{$referrer['pageViews']}}],
                    @endforeach
                ],
                type : 'donut'
            },
            donut: {
                title: "Ziyaretçi Kaynağı"
            }
        });

        var donut_chart3 = c3.generate({
            bindto: '#user-types',
            size: { width: 300 },
            color: {
                pattern: ['#3F51B5', '#FF9800', '#4CAF50', '#00BCD4', '#F44336']
            },
            data: {
                columns: [
                        @foreach($userTypes as $userType)
                    ['{{$userType[0]}}', {{$userType[1]}}],
                    @endforeach
                ],
                type : 'donut'
            },
            donut: {
                title: "Gelen Bağlantılar"
            }
        });

        var axis_categorized = c3.generate({
            bindto: '#c3-axis-categorized',
            size: { height: 400 },
            data: {
                columns: [
                    ['Oturumlar', <?php echo $analyticsPageViews ?>]
                ]
            },
            color: {
                pattern: ['#eb7312']
            },
            axis: {
                x: {
                    type: 'category',
                    tick: {
                        culling: {
                            max: 5
                        },
                        rotate: 0,
                        multiline: false
                    },
                    height: 40,
                    categories: [<?php echo $analyticsDates ?>],
                }
            },
            grid: {
                x: {
                    show: true
                }
            }
        });

    </script>
@endsection

resources/views/admin/dashboard_error.blade.php
@extends('admin.layouts.master')
@section('title', 'Smart Panel')
@section('css')
@endsection

@section('page-header')

<div class="col-md-12">
    <!-- Page header -->
    <div class="page-header">
        <div class="page-header-content">
            <div class="page-title">
                <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Dashboard</span> /Index</h4>
            </div>
        </div>
        <div class="breadcrumb-line breadcrumb-line-component bg-grey">
            <ul class="breadcrumb">
                <li><a href="{{ route('admin.dashboard.index') }}"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- /page header -->
@endsection

@section('content')
<div class="col-md-12">
    <div class="alert alert-info alert-styled-left alert-bordered">
        <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">Close</span></button>
        <span class="text-semibold">{{ $info['tr'] }}
    </div>
</div>

<div class="col-md-12">
    <!-- Basic responsive table -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title"><span class="text-highlight bg-primary">İletişim Formu</span></h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Adı Soyadı</th>
                    <th>Eklenme Tarihi</th>
                    <th>Durum</th>
                    <th class="text-center" style="width: 30px;"><i class="icon-menu-open2"></i></th>
                </tr>
                </thead>
                <tbody>
                @foreach($contact_forms as $contact_form)
                <tr>
                    <td>{{ $contact_form->name }}</td>
                    <td>{{ $contact_form->updated_at }}</td>
                    <td>
                        @if($contact_form->active == 1)
                            <span class="label label-success">Cevaplandı</span>
                        @endif

                        @if($contact_form->active == 0)
                            <span class="label label-warning">Cevap Bekliyor.</span>
                        @endif
                    </td>
                    <td class="text-center">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-menu9"></i>
                                </a>

                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="{{ route('admin.forms.edit', array('id' => $contact_form->id)) }}"><i class="icon-list"></i> Form Detayı</a></li>
                                </ul>
                            </li>
                        </ul>
                    </td>
                </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <!-- /basic responsive table -->
</div>
@endsection


@section('js')
<!-- Theme JS files -->
<script type="text/javascript" src="/cms/js/plugins/visualization/d3/d3.min.js"></script>
<script type="text/javascript" src="/cms/js/plugins/visualization/c3/c3.min.js"></script>
<script type="text/javascript" src="/cms/js/core/app.js"></script>
@endsection